### ISSUE TITLE
[visualization] Dashboard for CoCom backend

### ISSUE THREAD

**Issue by inishchith** [inishchith/gsoc-graal#11]
> This issue thread is for discussion related to visualizations that would be part of the (first) dashboard for the metrics produced with the help of Graal's CoCom backend.

(**Currently the analyzer is run at Repository-Level**)

- **Metrics**
  - [x] Overall CCN
  - [x] Overall LOC
  - [x] Overall Comments
- **Data Table** (https://github.com/inishchith/gsoc-graal/issues/11#issuecomment-505134143)
  - [x] File-Wise LOC, CCN, Comments, and Comment-Ratio(Comments/LOC)
  - [x] Overall CCN, LOC, Comments, Blanks, Functions for every project ( Instead of Individual metrics like above )
- **Visualizations**
  - [x] `Pie-Chart`:
       - Top Complex Files
       - Files with Most LOC
       - Most Commented Files or Most Comment to LOC Ratio
  - [x] `Evolution (Line-Chart):` (repository controlled via the in-place selector)
      - Lines of Code
      - Code Complexity
      - Comments
  - [ ] `XY-Plotting`: (controlled via selector)
      - LOC and Comments for every file at each point in time.
      - Mean & Median of LOC and Comments for all the files at each point in time.
- **Other ideas**
  - [x] Project/Repository/Module Selector

@valeriocos @aswanipranjal Please add some suggestions/ideas in case I've missed something out.
Thanks!

**Comment by inishchith** [comment]
**Overview Data Table**

- [x] **Overall CCN, LOC, Comments, Blanks, Functions for every project** (Instead of Individual metrics like above)
![Screenshot 2019-06-25 at 12 17 43 AM](https://user-images.githubusercontent.com/20226361/60043866-b845d080-96de-11e9-9440-0c9bba3ac4ff.png)

-------------------

- [x] **Top Complex files in a given software repository (Project)**
  - the issue with this visualization is that the latest commit analysis contains results of all the files. hence the changes cannot be tracked down to which commit made it more complex (evolution)

![Screenshot 2019-06-18 at 4 11 30 PM](https://user-images.githubusercontent.com/20226361/59675831-c1690600-91e3-11e9-9c5f-0c1227cb85f3.png)

**Comment by inishchith** [comment]
**Overview Other visualizations**

- [x] **Project-wise CCN(or other metrics) per day**
![Screenshot 2019-06-25 at 10 31 13 AM](https://user-images.githubusercontent.com/20226361/60070485-7e071e00-9734-11e9-8982-b3db0a5ea18e.png)
---------------------
- [x]  **After adding a filter for origin = [chaoss/grimoirelab-graal](https://github.com/chaoss/grimoirelab-graal)** for above
![Screenshot 2019-06-25 at 10 36 39 AM](https://user-images.githubusercontent.com/20226361/60070706-3634c680-9735-11e9-9bc2-45a679bb11c6.png)

**Comment by inishchith** [comment]
**Overview Metrics**

- [ ] **`TODO`**: Project-wise segregation
- [x]  **Overall CCN** 
![Screenshot 2019-06-18 at 11 45 38 AM](https://user-images.githubusercontent.com/20226361/59657546-ac2db080-91be-11e9-9a99-9196b91692c3.png)

- [x] **Overall LOC**
![Screenshot 2019-06-18 at 11 44 44 AM](https://user-images.githubusercontent.com/20226361/59657545-ac2db080-91be-11e9-9313-8f16b9235c17.png)

**Comment by valeriocos** [comment]
Good work @inishchith! A couple of questions/remarks:

- Did you check that the results obtained via the visualizations are correct?
- I can address the issue below if you want
> the issue with this visualization is that the latest commit analysis contains results of all the files. hence the changes cannot be tracked down to which commit made it more complex (evolution)

**Comment by inishchith** [comment]
@valeriocos 

> Did you check that the results obtained via the visualizations are correct?

Yes. All the results produced above are cross-checked except for: **` Top Complex files in a given software repository (Project)`**. I'm evaluating it again and will update you once done.

> I can address the issue below if you want ...

I'll be working on it today. But it'd be of great help if I could have your thoughts on it.

Also if could elaborate on the idea of the derived metrics (based on relations between two attributes) would be helpful :)

Thanks!

**Comment by valeriocos** [comment]
Thank you for the info @inishchith 

> I'll be working on it today. But it'd be of great help if I could have your thoughts on it.
I have added a comment at: https://github.com/chaoss/grimoirelab-graal/pull/39

WRT derived metrics, the idea is to add to the enriched items some fields that combine several attributes. For instance, for a file we have LOC and comments, we can add an enriched field that is `comments_ratio` = comments/LOC. Similar things could be done with functions or other attributes.
What do you think?

**Comment by inishchith** [comment]
> WRT derived metrics, the idea is to add to the enriched items some fields that combine several attributes. For instance, for a file we have LOC and comments, we can add an enriched field that is comments_ratio = comments/LOC. Similar things could be done with functions or other attributes.

The idea sounds good to me and can be easily incorporated in the current implementation. I'll have to think over how we can show this info on the dashboard (once we're ready with an initial one, we can re-iterate and have refined versions :) )

**Comment by inishchith** [comment]
- [x] **Data Table:**  Relation between LOC & Comments (Derived)


![Screenshot 2019-06-26 at 11 24 24 PM](https://user-images.githubusercontent.com/20226361/60203111-93ca2f80-9869-11e9-9720-baacd0db84dc.png)

@valeriocos Let me know what you think :)

**Comment by valeriocos** [comment]
It looks really cool! good job @inishchith

**Comment by inishchith** [comment]
@valeriocos Another way of showing top complex files in the available set of projects.
Let me know what you think :)



![Screenshot 2019-06-28 at 11 44 36 AM](https://user-images.githubusercontent.com/20226361/60321323-223dce80-999a-11e9-8d46-8e86bc0385f0.png)

**Note:**
1. The (selected)commit-sha is the latest commit
2. The inner ring(donut) is overall ccn of the repository

**Comment by inishchith** [comment]
@valeriocos @aswanipranjal @jgbarah Please let me know what you think of the (above shown) widgets.

Thanks!

**Comment by inishchith** [comment]
**We have our first version of CoCom dashboard available [here](http://tiny.cc/ug3x8y)**

(Addressing change in tag, we're now looking for refinements)

**Comment by aswanipranjal** [comment]
This looks really good @inishchith!

**Comment by valeriocos** [comment]
Thank you @inishchith for your work, find some comments below.

- All visualizations should have the labels set, you can do it by clicking on `Edit` and then for each visualization click on the corresponding gear and select `Customize panel`. An example of visualization with a label is `repository-project-selector` (on the dashboard it appears as `Repository/Project Selector`). Remember to save the dashboard :)
- The visualization `cocom_top_complex_files_pie` should be probably refactored, since it will generate a pie chart for each repo analyzed. Maybe we could have a visualization similar to `cocom_top_complex_files_pie_all`, which can work in combination with the selector `Repository/Project Selector`.
- It could be nice to have other visualizations similar to `cocom_project_wise_ccn_per_day` that focus on LOC, comments and number of functions.
- We could refactor the tables `cocom_file_wise_comments_ratio` and `cocom_top_complex_files_as_per_latest_commit` and try to merge them in just one. If possible, the new table could have columns that focus on top X files that have the highest number of LOC, CCN and poorest `comments_ratio`.
- It could be useful to be able to show in a table or chart, all files having more than X LOC, CCN. This may help end-users to drive refactorings. I guess this can be probably done with a selector.
- I like the visualization `cocom_project_wise_metric_table`, however for large repos it may not be useful as it is. A possible solution would be to enhance the selector `Repository/Project Selector` to include also a filter for files. Thus, the end-user could be select a given file (or a subset of them).
- It could be useful to know the LOC, CCN, comments per module. We could get this info using the path of files. This info could be easily calculated by the enricher.

WDYT?

**Comment by inishchith** [comment]
> All visualizations should have the labels set, you can do it by clicking on `Edit` and then for each visualization click on the corresponding gear and select `Customize panel`. An example of visualization with a label is `repository-project-selector` (on the dashboard it appears as `Repository/Project Selector`). Remember to save the dashboard :)

Thanks, I missed this. I'll add the labels.

> The visualization `cocom_top_complex_files_pie` should be probably refactored, since it will generate a pie chart for each repo analyzed. Maybe we could have a visualization similar to `cocom_top_complex_files_pie_all`, which can work in combination with the selector `Repository/Project Selector`.

Yes, I had addressed this issue last week. And yes, we can use the selector to enhance the results and get this to work!. About`cocom_top_complex_files_pie_all`: I've corrected it now, Please have a look now. 

> It could be nice to have other visualizations similar to `cocom_project_wise_ccn_per_day` that focus on LOC, comments, and number of functions.

Yes. I had added for CCN just to get the idea clear. Getting it ready for others would be easier. I'll add those :)

> We could refactor the tables `cocom_file_wise_comments_ratio` and `cocom_top_complex_files_as_per_latest_commit` and try to merge them in just one. If possible, the new table could have columns that focus on top X files that have the highest number of LOC, CCN and poorest `comments_ratio`.

Sounds good 👍 

> It could be useful to be able to show in a table or chart, all files having more than X LOC, CCN. This may help end-users to drive refactorings. I guess this can be probably done with a selector.

Yes. This would be great to have. 

> I like the visualization `cocom_project_wise_metric_table`, however, for large repos, it may not be useful as it is. A possible solution would be to enhance the selector `Repository/Project Selector` to include also a filter for files. Thus, the end-user could be select a given file (or a subset of them).

The `cocom_project_wise_metric_table` was supposed to be working as an overview table for all the available project, but I like the idea of providing information for files via the selector. I'll think over this, get a mock reference ready and update you :)

> It could be useful to know the LOC, CCN, comments per module. We could get this info using the path of files. This info could be easily calculated by the enricher.

The idea seems interesting, but not sure about it's implementation at the enricher side, can you elaborate a bit, That might help me. Thanks!


- @valeriocos Sorry for the delayed response.
Thanks for the suggestions, I'll be working on them one-by-one and update you on this thread in case I have questions or need feedback. 

Thanks!

**Comment by valeriocos** [comment]
Sorry for the late reply @inishchith 

> The idea seems interesting, but not sure about it's implementation at the enricher side, can you elaborate a bit, That might help me. Thanks

A possible solution would be to split the file_path by `/` and store the results in a list. For instance, let's suppose we have a `file_path` in the enriched index like `"graal/backends/core/analyzers/flake8.py"`, the list could contain `["graal/", "graal/backends/", ""graal/backends/core/", "graal/backends/core/analyzers/"]`

I can push some code to the enricher, if it can help. WDYT?

> Thanks for the suggestions, I'll be working on them one-by-one and update you on this thread in case I have questions or need feedback.](url)

Great, thanks!

**Comment by inishchith** [comment]
> A possible solution would be to split the file_path by / and store the results in a list. For instance, let's suppose we have a file_path in the enriched index like "graal/backends/core/analyzers/flake8.py", the list could contain ["graal/", "graal/backends/", ""graal/backends/core/", "graal/backends/core/analyzers/"]
> I can push some code to the enricher, if it can help. WDYT?

@valeriocos I like the idea, and yes that would be of great help. 
Thanks a lot :)

**Comment by inishchith** [comment]
**Tracking the above improvements:**
- [x] Add labels to visualizations 
- [x] Refactor `cocom_top_complex_files_pie`(similar to `cocom_top_complex_files_pie_all`)
- [x] Visualizations (similar to `cocom_project_wise_ccn_per_day`) that focus on LOC, Comments and Functions
- [x] Refactor data-tables and add new columns ( `cocom_file_wise_comments_ratio` & `cocom_top_complex_files_as_per_latest_commit` + `loc`, `comments_ratio` )
- [x] Viz. for `more than X LOC, and other`. ( slider added )
- [x] Subset of Files selector
- [x] `Module-level` information (via. enricher)
- [ ] Work on Repository/Project Selector. (Organize)
- [ ] Organize dashboard (Discard+Widget placements)

@valeriocos We can add more improvements to this over-time. let me know what you think.


Thanks!

**Comment by valeriocos** [comment]
That's perfect @inishchith ! Let me know if I can help you in some way.

**Comment by inishchith** [comment]
@valeriocos Thanks. Can you have a look at the 5th point (about metric table) `cocom_project_wise_metric_table_all` [here](https://grimoirelab-incubator.biterg.io/app/kibana#/visualize/edit/68b64b40-9c1e-11e9-82c4-37956b0c932a?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-1y,mode:quick,to:now))&_a=(filters:!(),linked:!f,query:(language:lucene,query:''),uiState:(vis:(params:(config:(searchKeyword:''),sort:(columnIndex:2,direction:desc)))),vis:(aggs:!((enabled:!t,id:'1',params:(aggregate:concat,field:ccn,size:1,sortField:commit_date,sortOrder:desc),schema:metric,type:top_hits),(enabled:!t,id:'6',params:(aggregate:concat,field:loc,size:1,sortField:commit_date,sortOrder:desc),schema:metric,type:top_hits),(enabled:!t,id:'5',params:(aggregate:concat,field:comments_ratio,size:1,sortField:commit_date,sortOrder:desc),schema:metric,type:top_hits),(enabled:!t,id:'2',params:(field:origin,order:desc,orderBy:_term,size:10),schema:bucket,type:terms),(enabled:!t,id:'4',params:(field:file_path,order:desc,orderBy:_term,size:100),schema:bucket,type:terms)),params:(perPage:10,showMeticsAtAllLevels:!f,showPartialRows:!f,showTotal:!f,sort:(columnIndex:!n,direction:!n),totalFunc:sum),title:cocom_project_wise_metric_table_all,type:table)))

1. I tried to get rid of the `commit_sha` field in this case, have to cross-check if the results produced are correct.
2. We can remove `Project Wise Complex Files` from the dashboard as we now have `Top 10 Complex Files` Pie. WDYT?
3. How do you mark a viz. as experimental? ( couldn't find a way 🙈 )

**Comment by valeriocos** [comment]
`1. I tried to get rid of the commit_sha field in this case, have to cross-check if the results produced are correct.`
OK

`2. We can remove Project Wise Complex Files from the dashboard as we now have Top 10 Complex Files Pie. WDYT?`

Sure! it make sense

`3. How do you mark a viz. as experimental? ( couldn't find a way see_no_evil )`
They are set automatically by Kibana (I guess)

**Comment by valeriocos** [comment]
I've checked the cocom dashboard, it looks great @inishchith!
Find some comments below:

1. We could split the Graal - Code Complexity visualization in 3:
- one metric viz for Overall Max of Sum of Code Complexity
- one metric viz for Overall Max of Sum of loc
- a new metric viz for Max of Sum of comments

Each of these metric vizs should be on a row together with the corresponding line chart.

2. The visualization Project Wise Complex Files should be removed (as we agreed, right?)

3. We could expand the Top 10 Complex Files visualization and put it on the same row of Repository/Project Selector (which should be renamed)

4. The table comments ratio could be changed to include module, code complexity and lines of code, and project. It could work in combination with the Repository/Project Selector
WDYT?


If you think it's easier, I can make a pass on the dashboard and make the modifications above.

Thanks!

**Comment by inishchith** [comment]
@valeriocos Sorry for the delayed response.

I've made some changes to the existing viz. But it would be great if you could pass on the dashboard once and feel free to make modifications. 

Thanks!

**Comment by inishchith** [comment]
@valeriocos 

1. As I was going through the dashboard for verification of results, found out the following mistake
- **`cocom_top_complex_files_pie_all`** is incorrect
  - In the first step, we form a `Bucket` with 10 files of Max CNN which is incorrect as there might be improvements made to the file(and leading to lower CCN). 

I found a solution(**`cocom_top_complex_files_pie`**) of picking the latest commit, which uses the inner ring for the sum of the selected metric on the latest commit and the outer ring to pick the most complex files in that commit. I think this accurate and the results could be refined using the selector (by picking the repository)

2. I've updated the dashboard as per the 1st comment on this issue(Flow). There are some additions to be worked on(unchecked ones). Please do have a look. 

Thanks :)

**Comment by inishchith** [comment]
@valeriocos Please do check the above comment.

Also, I've added **`cocom_loc_comments_all`** which can be refined by selecting a repository.

- [x]  Line-Chart for LOC and Comments 
   - a line each and repository controlled via the in-place selector. (Incorporating Code Complexity(CCN) metric would be difficult due to the difference in scale)

Please do have a look. Thanks :)

**Comment by inishchith** [comment]
**Updates:**

`Note:` We have done some necessary rearrangements to the widgets on the dashboard and updated the labels. 

Require your suggestion here: @aswanipranjal @jgbarah 

- Currently, there are 3 Pie-Charts on the dashboard, the sections of it have labels (of file-name), we were wondering if we can remove the section labels(as it looks a bit cluttered as of now). What do you think?

**Comment by inishchith** [comment]
closing in reference to https://github.com/chaoss/grimoirelab-sigils/pull/380
