### ISSUE TITLE
[visualization] Dashboard for CoLic backend

### ISSUE THREAD

**Issue by inishchith** [inishchith/gsoc-graal#14]
> This issue thread is for discussion related to visualizations that would be part of the (first) dashboard for the metrics produced with the help of Graal's CoLic backend.

- **Metrics**
  - [x] License Count: Number of licensed files 
  - [x] Copyright Count: Number of copyrighted files 
- **Data Tables**
  - [x] Files with no license definition
  - [x] Files with no copyright definition 
  - [x] File-wise license definition
  - [x] File-wise copyright Definition
- **Visualizations**
  - [x] All licenses (Pie)
  - [x] All copyright definition (Pie)
  - [x] Line-Chart to show the evolution of the number of licensed/copyrighted files against the ones without it.
  - [x] A Line-chart to show the evolution of the number of files for each license/copyright definition against the ones without it.
- **Other Ideas**
  - [x] Project/Repository/Module Selector

**Comment by inishchith** [comment]
### License Related

- **Data Tables:** Files with no license definition

![Screenshot 2019-07-04 at 7 21 24 PM](https://user-images.githubusercontent.com/20226361/60671551-f1293680-9e90-11e9-9f1c-570fee1c1d1a.png)


- **Visualizations:**  All licenses across projects (Pie)

![Screenshot 2019-07-04 at 6 59 54 PM](https://user-images.githubusercontent.com/20226361/60670284-ed47e500-9e8d-11e9-9741-85ab76c38bcb.png)


- **Data Tables:** File-wise license definition

![Screenshot 2019-07-04 at 7 18 50 PM](https://user-images.githubusercontent.com/20226361/60671395-a14a6f80-9e90-11e9-8bca-98663be22de8.png)

--------------------------
### Copyright Related

- **Data Tables:** Files with no copyright definition

![Screenshot 2019-07-04 at 7 20 27 PM](https://user-images.githubusercontent.com/20226361/60671502-d5259500-9e90-11e9-9a67-cf7098dac3f2.png)

- **Visualizations:**  All copyright definition across projects (Pie)

![Screenshot 2019-07-04 at 7 15 58 PM](https://user-images.githubusercontent.com/20226361/60671204-3731ca80-9e90-11e9-86e2-e1b7269a9ff9.png)


- **Data Tables:** File-wise copyright Definition

![Screenshot 2019-07-04 at 7 17 25 PM](https://user-images.githubusercontent.com/20226361/60671305-6e07e080-9e90-11e9-9b0d-e5e0605ca2ce.png)

------------------------

### Selector 

- **This will help produce results at file and module level into the above viz.**

![Screenshot 2019-07-04 at 7 24 31 PM](https://user-images.githubusercontent.com/20226361/60671751-64cb4380-9e91-11e9-8d35-f62fd2aed75a.png)



**First Iteration of CoLic Dashboard can be found [here](http://tiny.cc/yoy88y)**

@valeriocos @aswanipranjal @jgbarah Please let me know what you think of the (above shown) widgets.

I'll be adding more notes related to improvements soon :)

Thanks!

**Comment by valeriocos** [comment]
Really nice work @inishchith 

I'm not sure about the tables. Maybe we could add two bar charts or line charts to show the evolution of files with license and copyright info, and have just a table that shows details about a file or a module
(it would work on combination with the selector). WDYT?

**Comment by inishchith** [comment]
Thanks, @valeriocos 

> I'm not sure about the tables. Maybe we could add two bar charts or line charts to show the evolution of files with license and copyright info, and have just a table that shows details about a file or a module. (it would work on combination with the selector). WDYT?

Agree with you. We should have more viz. Data-table was just an initial exploration from my side. 
I'll try to work on them and share results :)

**Comment by inishchith** [comment]
- [ ] **TODO:** Inspect correctness and verbosity of the data(attributes) produced(mainly copyright info.) by Graal’s CoLic Backend.


@valeriocos I've updated the 1st comment on this issue as per additions/improvements to be made.

**Comment by inishchith** [comment]
@valeriocos @jgbarah @aswanipranjal The current status of CoLic Dashboard can be found [here](https://grimoirelab-incubator.biterg.io/app/kibana#/dashboard/07dadc50-9c19-11e9-82c4-37956b0c932a). (like one shown below)

![KnpTgmn6WI](https://user-images.githubusercontent.com/20226361/60988891-44ecc180-a362-11e9-82a9-c04e03052157.gif)

**Comment by inishchith** [comment]
- **`Line-Chart`** ( Evolution of Licensed & Copyrighted files )

![Screenshot 2019-07-23 at 12 03 28 PM](https://user-images.githubusercontent.com/20226361/61688234-1992ab00-ad42-11e9-8dcc-9ed0d2f78fbc.png)

**Comment by inishchith** [comment]
closing in reference to https://github.com/chaoss/grimoirelab-sigils/pull/380
