### ISSUE TITLE
[refinements] Revamp Index and visualizations to appropriate levels

### ISSUE THREAD

**Issue by inishchith** [inishchith/gsoc-graal#15]
> The need of the task is in reference to the new ideas and improvements made to the structuring of the data(levels) after discussions with mentors during the weekly meetings.

- **Task:** Migrate/Revamp current visualizations, part of the dashboards to their appropriate levels of indexes ( study, commit-level, etc.) for `CoCom` & `CoLic` dashboards.

**Comment by inishchith** [comment]
### CoCom Dashboard

- We had recently moved out logic from `repository-level` to `file-level + study` and hence the visualizations required revamping. Below is a table showing the equivalent viz. of the earlier implementation.

| From   | To | Uses |
| :-------------: | :---------: | :---------: | 
| cocom_project_wise_metric_table | cocom_study_project_wise_metric_table | study index |
| cocom_project_wise_evolution_loc | cocom_study_project_wise_evolution_loc | study index |
| cocom_main_metrics_loc | cocom_study_main_metrics | study index |
| cocom_file_wise_metric_table_all | cocom_study_file_wise_metric_table_all | File-level data |
| cocom_top_commented_files_`pie` | _yet to be added_ | - |


**Note:**
- The `cocom_project_wise_evolution_loc` viz. had calculation error due to implementation which has been fixed in `cocom_study_project_wise_evolution_loc` and can be delegated with the help of Selector.
- Earlier we had `module-level` inspection on the line chart which used to work well, now it's restricted to only the data-table(`cocom_file_wise_metric_table_all`) as the other parts are migrated to the study logic.
- I was experimenting with **TimeLion** (cocom_study_ccn_line), it seems we can show a line per metric across repositories, which can be delegated (via Selector). Let me know what you think, we can probably replace the line charts :)

@valeriocos above are some of the things that I encountered during the revamping task, we can discuss more and fix some while iterating through the dashboard again.

Thanks!

**Comment by valeriocos** [comment]
Thank you @inishchith for the summary and proposals. 
I checked the cocom and colic dashboards and they look really nice! good job!

WRT `module-level` and `timelion` we can leave them as enhancement/future work. We can focus on them as soon as we have iterated over the dashboards. WDYT?

**Comment by inishchith** [comment]
Thanks! @valeriocos 

> WRT module-level and timelion we can leave them as enhancement/future work. We can focus on them as soon as we have iterated over the dashboards. WDYT?

Yes. Agree with you.

**Comment by inishchith** [comment]
Closing in reference to completion of the task. ([reference](https://inishchith.github.io/blog/2019/07/coding-period-2-8.html))
