### ISSUE TITLE
[discussion] Considering relevant attributes from Graal for Visualization

### ISSUE THREAD

**Issue by inishchith** [inishchith/gsoc-graal#6]
WRT [Integration Task: Graal with ELK](https://github.com/inishchith/gsoc-graal/issues/4)

@valeriocos @jgbarah @aswanipranjal: This issue thread is for discussion related to what attributes from the results produced by `Graal` are relevant and should be considered for visualization and creation of dashboards. 

----------------
**Note:**
1. Currently, the integration task is conducted for `CoCom` backend only, so the attributes in consideration are - 
```
analysis = [
...
 {
  "ccn": 19,
  "avg_ccn": 2.111111111111111,
  "avg_loc": 9.11111111111111,
  "avg_tokens": 64,
  "num_funs": 9,
  "loc": 129,
  "tokens": 786,
  "ext": "py",
  "blanks": 48,
  "comments": 63,
  "file_path": "graal/codecomplexity.py"
}
...
]
```

**Comment by inishchith** [comment]
@valeriocos @jgbarah @aswanipranjal As per our last meeting ( on Friday, 7th June ). 
We had thought to visualize changes over some of the above attributes over a (configurable) amount of time. I'd be working on it this week ( as discussed ) and ask doubts/questions here ( if any)

Any thoughts or suggestions on it?

Thanks!

**Comment by inishchith** [comment]
[ As we can see the above-referenced issues ]

**[analyzer] Fix results for deleted files: https://github.com/chaoss/grimoirelab-graal/issues/35**
> There were some issues/redundancy in the results retrieved from the (CoCom) Backend,  which can be fixed via this issue.

**[cocom] Evaluating results with repository level analysis: https://github.com/chaoss/grimoirelab-graal/issues/36**
> We had discussed of visualizing some of the attributes for a given repository on a given point of time. There could be two approaches: 
> - The current implementation of Graal's CoCom Backend produces results over the files affected for a given commit, Hence, in order to produce the visualization, we have to pick the last updated values of all the files and perform sum total of the particular attribute, which would be a bit complex to implement in Kibana. ( though we've been discussing how to implement this efficiently ).
> - Alter the current implementation of Graal's CoCom Backend to have an option to produce results at the repository level, which would make it easier to implement the visualization along with the evolution of the attribute (using serial diff). **The above issue is for the evaluation of this idea ( which will also be discussed in this week's meeting. (Friday)**


@valeriocos Please let me know in case I missed something out. Thanks :)

**Comment by inishchith** [comment]
@valeriocos @aswanipranjal @jgbarah

I've worked on the repository level analysis and could produce the following results ( which can be 
further improved after some discussion )

Repository: [chaoss/grimoirelab-perceval](https://github.com/chaoss/grimoirelab-perceval)

---------------------
<div align="center">
<b> [ Total Lines of Code at a given point of time ( here per month ) ] </b>
</div>

![Screenshot 2019-06-12 at 7 46 50 PM](https://user-images.githubusercontent.com/20226361/59359014-3dc69980-8d4b-11e9-880c-de1ba19a4da5.png)

 ---------------------

<div align="center">
<b> [ Total Code Complexity at a given point of time ( here per month ) ] </b>
</div>

![Screenshot 2019-06-12 at 7 48 09 PM](https://user-images.githubusercontent.com/20226361/59359015-3dc69980-8d4b-11e9-88a0-2a94a1130961.png)

**Comment by inishchith** [comment]
> **Using Kibana's TimeLion + Analysis data (Repository Level)**

<div align="center">
       <b>[ Code Complexity per week ]</b>
</div>

![Screenshot 2019-06-13 at 11 23 55 PM](https://user-images.githubusercontent.com/20226361/59455813-9329a600-8e32-11e9-9f07-584c626478a9.png)

--------------------

<div align="center">
       <b>[ Code Complexity v/s Lines of Code per week ]</b>
</div>

![Screenshot 2019-06-13 at 11 24 35 PM](https://user-images.githubusercontent.com/20226361/59455814-9329a600-8e32-11e9-8a55-d98c70daf42f.png)

**Comment by valeriocos** [comment]
Thank you @inishchith , did you try to use timelion with the non repository-level data?

**Comment by inishchith** [comment]
@valeriocos Sorry for the delayed response.
The idea was to sum the values of the latest data. Yes, I did try it, but couldn't get the configuration correctly. I'm still looking up for related examples

**Comment by inishchith** [comment]
In reference to the repository-level analysis using lizard. ( REF. https://github.com/chaoss/grimoirelab-graal/pull/38#issuecomment-502788055) 

Repository: [chaoss/grimoirelab-perceval](https://github.com/chaoss/grimoirelab-perceval)

<div align="center">
<b> [ Total Lines of Code after latest commit] </b>
</div>

![Screenshot 2019-06-18 at 11 44 44 AM](https://user-images.githubusercontent.com/20226361/59657545-ac2db080-91be-11e9-9313-8f16b9235c17.png)

-------------------


<div align="center">
<b> [ Total Code Complexity after latest commit ] </b>
</div>

![Screenshot 2019-06-18 at 11 45 38 AM](https://user-images.githubusercontent.com/20226361/59657546-ac2db080-91be-11e9-9a99-9196b91692c3.png)

-------------------

<div align="center">
<b> [ Most Complex files after latest commit ] </b>
</div>

![Screenshot 2019-06-18 at 4 11 30 PM](https://user-images.githubusercontent.com/20226361/59675831-c1690600-91e3-11e9-9c5f-0c1227cb85f3.png)

(issue with the above is that the latest commit analysis contains results of all the files. hence the changes cannot be tracked down to which commit made it more complex ( evolution ) )

**Comment by inishchith** [comment]
closing in reference #11
